apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasources.yml: |-
    apiVersion: 1
    datasources:
    - name: MyPrometheus
      type: prometheus
      url: http://prometheus-service:9090
      isDefault: true
