apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: kube-state-metrics
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - kube-state-metrics.kube-system.svc.cluster.local:8080
    rule_files:
    - /etc/prometheus/myrules.yml
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - "alertmanager:9093"
  myrules.yml: |
    groups:
    - name: podcountalert
      rules:
      - alert: PODCountAlert
        expr: sum(kube_pod_info{namespace!="kube-system"}) > 15
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "warning more than 15 non-system pods are running"
          summary: "too many non-system pod count"
